### PR TITLE
Add __self__ and __func__ for bound templates

### LINKED ISSUE #3: BoundViewTemplate should use `__self__` and `__func__`
See zopefoundation/z3c.pt#9

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #3.

Currently based on #2; only the tip commit is relevant here.

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
LGTM

**Review by icemac — APPROVED** [review]
LGTM besides the failing TravisCI.

**Comment by jamadden** [comment]
Rebased on master for merge.

**Comment by jamadden** [comment]
Thank you!

Could we get a PyPI release when convenient, please?

**Comment by icemac** [comment]
@jamadden Thank you for your work on this package. I added you as owner of this package on PyPI.

**Comment by jamadden** [comment]
Thank you! 3.0.0 has been released to PyPI.

**Pull request merged**
